server:
  port: 8813
spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:127.0.0.1}:3306/orderdb
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform:
    hibernate:
      ddl-auto: update
  application:
    name: ORDER-SERVICE
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:9232}
  #resilience4j :
   # circuitbreaker :
    #  instances :
     #   external :
      #   event-consumer-buffer-size: 10
      #   failure-rate-threshold: 50
      #   minimum-number-of-calss: 5
      #    automatic-transition-from-open-to-half-open-enabled : true
      #    wait-duration-in-open-state : 5s
      #    permitted-number-of-calls-in-half-open-state : 3
      #    sliding-window-size : 10
      #    sliding-window-type : COUNT_BASED


#  cloud
#    config:
#      import-check:
#        enabled: false
eureka:
  instance:
    prefere-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    servie-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http:localhost:8761/eureka}

